version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=app-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

