version: '3.1'
services:
  mysql:
    image: library/postgres:12-alpine
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app-db
      - POSTGRES_USER=user

